- name: Add GPG key from Treasure Data, Inc
  command: rpm --import https://packages.treasuredata.com/GPG-KEY-td-agent

- name: Add td repo
  become: yes
  template: src=fluentd.repo.j2 dest=/etc/yum.repos.d/fluentd.repo

- name: Install td-agent
  become: yes
  yum: name=td-agent-{{ td_agent_version }} state=present

- name Change td-agent user mode
  become: yes
  command: /usr/sbin/usermod -d /var/lib/td-agent td-agent

- name Create home dir
  become: yes
  file: path=/var/lib/td-agent state=directory owner=td-agent group=td-agent

- name: Copy conf files
  become: yes
  template: src=td-agent.conf.j2 dest=/etc/td-agent/td-agent_{{ item }}.conf
  with_items: {{ fluentd_ports }}

- name: Copy service files
  become: yes
  template: src=td-agent.service.j2 dest=/usr/lib/systemd/system/td-agent_{{ item }}.service
  with_items: {{ fluentd_ports }}

- name Copy Gemfile
  become: yes
  copy: src=Gemfile dest=/etc/td-agent/Gemfile

- name: Enable td-agent.service
  become: yes
  systemd:
    name: td-agent_{{ item }}.service
    state: restarted
    daemon_reload: yes
    enabled: yes
  with_items: {{ fluentd_ports }}
